language: go

go:
  - 1.7
  - tip


before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck
  - go get github.com/mattn/goveralls
  - go get github.com/opennota/check/cmd/structcheck
  - go get github.com/opennota/check/cmd/varcheck
  - go get github.com/jgautheron/goconst/cmd/goconst
  - go get honnef.co/go/simple/cmd/gosimple
  - go get honnef.co/go/staticcheck/cmd/staticcheck

script:
  - go test -race ./...
  - "! gofmt -d $(find . -type f -name '*.go' -not -path './vendor/*') 2>&1 | read"
  - rm -Rf vendor
  - go vet ./...
  - errcheck ./...
  - golint -set_exit_status ./...
  - structcheck ./...
  - varcheck ./...
  - gosimple ./...
  - staticcheck ./...
  - goconst ./...
